language: go
git:
  depth: 50
sudo: required
install:
- curl https://get.dgraph.io -sSf | bash /dev/stdin "-y"
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
before_script:
- go get -t -v ./...
- dgraph zero &
- ZERO_PID=$!
- dgraph alpha --lru_mb 1024 &
- SERVER_PID=$!
script:
- go test -v -covermode=count -coverprofile=coverage.out
- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci"
after_script:
- kill -2 $SERVER_PID
- kill -2 $ZERO_PID
